### ISSUE TITLE
Slow when calling several times.

### ISSUE THREAD

**Issue by zhg-kj** [BlakeStevenson/populartimes.js#2]
I am using populartimes.js to add populartimes to my markers through a loop. However, the call ends up being very slow. I have tried blocking the images and CSS but at best I can only reach about 4 seconds to get the data for each marker. Is there any other way to optimize?

**Comment by BlakeStevenson** [comment]
I just pushed some optimizations, but I was unable to get it to load any faster than 5 seconds or so, which is down from 7-8 seconds. It appears that since the page has to load various scripts that retrieve data from other places, I am unable to make any further optimizations (blocking JS, etc.) without breaking the script.
